export const DESTINATIONS = {
        Domestic: [
        "Agartala",
        "Agra",
        "Ahmedabad",
        "Ajanta",
        "Ajmer",
        "Alappuzha",
        "Alibaug",
        "Aligarh",
        "Allahabad",
        "Almora",
        "Amarkantak",
        "Amravati",
        "Amritsar",
        "Anantapur",
        "Anantnag",
        "Auli",
        "Aurangabad",
        "Auroville",
        "Ayodhya",
        "Badami",
        "Badrinath",
        "Balasore",
        "Bandhavgarh",
        "Bandipur",
        "Bangalore",
        "Baratang Island",
        "Barot",
        "Bastar",
        "Bekal",
        "Bengaluru",
        "Berhampur",
        "Bhimbetka",
        "Bhopal",
        "Bhubaneswar",
        "Bhuj",
        "Bijapur",
        "Bikaner",
        "Bir Billing",
        "Bodh Gaya",
        "Bolpur",
        "Chamba",
        "Chandigarh",
        "Chennai",
        "Cherrapunji",
        "Chidambaram",
        "Chikmagalur",
        "Chilika",
        "Chitrakoot",
        "Chittorgarh",
        "Chopta",
        "Coimbatore",
        "Cooch Behar",
        "Coorg",
        "Cuttack",
        "Dalhousie",
        "Darjeeling",
        "Dehradun",
        "Delhi",
        "Deoghar",
        "Digha",
        "Diskit",
        "Diu",
        "Dras",
        "Dumboor",
        "Dwarka",
        "Dzukou Valley",
        "Fatehpur Sikri",
        "Gandhinagar",
        "Gangtok",
        "Goa",
        "Gokarna",
        "Greater Noida",
        "Guntur",
        "Gurugram",
        "Guwahati",
        "Gwalior",
        "Hajo",
        "Halebidu",
        "Hampi",
        "Haridwar",
        "Havelock Island",
        "Hemis",
        "Hooghly",
        "Hyderabad",
        "Indore",
        "Jabalpur",
        "Jaipur",
        "Jaisalmer",
        "Jalpaiguri",
        "Jammu",
        "Jhansi",
        "Jim Corbett",
        "Jodhpur",
        "Joshimath",
        "Junagadh",
        "Kadapa",
        "Kangra",
        "Kanha",
        "Kannur",
        "Kanpur",
        "Kanyakumari",
        "Kargil",
        "Kaziranga",
        "Kedarnath",
        "Kendujhar",
        "Keonjhar",
        "Kevadia",
        "Khajuraho",
        "Kinnaur",
        "Kishtwar",
        "Kochi",
        "Kodaikanal",
        "Kolhapur",
        "Kolkata",
        "Konark",
        "Kovalam",
        "Kozhikode",
        "Kufri",
        "Kullu",
        "Kumarakom",
        "Kurnool",
        "Leh",
        "Lonavala",
        "Lucknow",
        "Madurai",
        "Mahabalipuram",
        "Majuli",
        "Manali",
        "Manas",
        "Mandi",
        "Mandu",
        "Mangalore",
        "Manikaran",
        "Matheran",
        "Mathura",
        "McLeod Ganj",
        "Meerut",
        "Mount Abu",
        "Mumbai",
        "Munnar",
        "Murshidabad",
        "Murudeshwar",
        "Mussoorie",
        "Mysore",
        "Nagpur",
        "Nainital",
        "Namchi",
        "Narkanda",
        "Nashik",
        "Neil Island",
        "Nelliyampathy",
        "New Delhi",
        "Noida",
        "Nubra Valley",
        "Ooty",
        "Orchha",
        "Pachmarhi",
        "Pahalgam",
        "Palampur",
        "Patna",
        "Pelling",
        "Porbandar",
        "Port Blair",
        "Puducherry",
        "Pune",
        "Puri",
        "Purulia",
        "Pushkar",
        "Puttaparthi",
        "Rajahmundry",
        "Rameswaram",
        "Ranchi",
        "Ranikhet",
        "Rann of Kutch",
        "Ratnagiri",
        "Ravangla",
        "Rishikesh",
        "Rourkela",
        "Sambalpur",
        "Sarnath",
        "Satara",
        "Sawai Madhopur",
        "Shimla",
        "Shirdi",
        "Shivamogga",
        "Shoja",
        "Siliguri",
        "Sivasagar",
        "Somnath",
        "Spiti Valley",
        "Srinagar",
        "Srisailam",
        "Sundarbans",
        "Tarkarli",
        "Tawang",
        "Thanjavur",
        "Thekkady",
        "Thiruvananthapuram",
        "Tirunelveli",
        "Udaipur",
        "Udhampur",
        "Ujjain",
        "Unakoti",
        "Uttarkashi",
        "Vadodara",
        "Varanasi",
        "Varkala",
        "Vijayawada",
        "Visakhapatnam",
        "Vizianagaram",
        "Vrindavan",
        "Wayanad",
        "Yercaud"
    ],
        
    International: [
        "Australia",
        "Brazil",
        "Cambodia",
        "Canada",
        "China",
        "France",
        "Germany",
        "Greece",
        "Indonesia",
        "Italy",
        "Japan",
        "Malaysia",
        "Maldives",
        "New Zealand",
        "Singapore",
        "Spain",
        "Thailand",
        "United Arab Emirates",
        "United Kingdom",
        "United States"
    ],
};

export const PACKAGE_TYPES = [
    "Budget",
    "Family",
    "Honeymoon",
    "Adventure",
    "Luxury",
    "Cultural",
    "Nature & Wildlife",
    "Grand Tour"
];

export const HOTEL_CATEGORIES = [
    "3 Star",
    "4 Star",
    "5 Star"
];

export const BEST_FOR = [
    "Solo",
    "Couples",
    "Family",
];

export const ACTIVITIES = [
    "Adventure",
    "Beach",
    "Culture",
    "Sightseeing",
    "Wildlife",
    "Nature",
    "Trekking",
    "Shopping",
    "Religious",
    "Photography",
    "Camping",
    "Boating",
    "Snorkeling",
    "Scuba Diving",
    "Safari",
    "Hiking",
    "Food Tour",
    "City Tour",
    "Nightlife",
    "Museum"
];